# Generated by Django 6.0.2 on 2026-02-23 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0002_project_featured_project_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='live_demo_link',
            new_name='linkedin_link',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='project',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='project',
            name='slug',
        ),
    ]
